language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - pip install pytest-timeout
# command to run tests
script:
    - python setup.py build_ext -i
    - py.test -v
    - python regrtest.py -v test_threading
